### PR TITLE
Translated to Bosnian

### PR DESCRIPTION
**Pull request by hajro92**

### CODE REVIEW

**Comment by m1k1o** [comment]
Looks good! Thanks.

**Comment by hajro92** [comment]
> Your PR has been labeled as "invalid" or "spam" by a maintainer and won't count toward winning Hacktoberfest.

Why is that

**Comment by m1k1o** [comment]
@hajro92 I don't know, I simply merged that. But I see, your account on that commit was not recognized correctly. Maybe something about that.

**Comment by hajro92** [comment]
> Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.

I think this is a problem.

**Comment by hajro92** [comment]
> @hajro92 I don't know, I simply merged that. But I see, your account on that commit was not recognized correctly. Maybe something about that.

Can you add label "hacktoberfest-accepted" to it? Thanks :)

**Comment by m1k1o** [comment]
@hajro92 sure;)

**Pull request merged**
